on: [push, pull_request]

name: glad2

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write


env:
  WINEDLLOVERRIDES: mscoree,mshtml=
  WINEARCH: win64
  WINE: wine

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Setup PyPy3.9
        uses: actions/setup-python@v5
        with:
          python-version: 'pypy3.9'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install dependencies
        run: |
          sudo env DEBIAN_FRONTEND=noninteractive dpkg --add-architecture i386
          sudo env DEBIAN_FRONTEND=noninteractive apt-get update
          sudo env DEBIAN_FRONTEND=noninteractive apt-get install -y gcc g++ gcc-mingw-w64 g++-mingw-w64 cargo rustc libglfw3-dev wine wine32 wine64 winetricks xvfb libxxf86vm-dev libxi-dev libxcursor-dev libxinerama-dev
      - name: Setup environment
        run: |
          rm -rf .wine
          mkdir -p .wine
          export WINEPREFIX="$(pwd)/.wine"

          winetricks nocrashdialog
      - name: Run Tests
        run: PRINT_MESSAGE=1 xvfb-run --auto-servernum ./utility/test.sh
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: unit-tests
          path: 'test-report.xml'

  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: test
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: test-results

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: "test-results/*.xml"
